name       : websocketpp
version    : 0.8.2
release    : 1
source     :
    - https://github.com/zaphoyd/websocketpp/archive/refs/tags/0.8.2.tar.gz : 6ce889d85ecdc2d8fa07408d6787e7352510750daa66b5ad44aacb47bea76755
license    : BSD-3-Clause
homepage   : https://www.zaphoyd.com/projects/websocketpp/
component  : programming.library
summary    : C++ websocket client/server library
description: |
    WebSocket++ is a header only C++ library that implements RFC6455 The WebSocket Protocol. It allows integrating WebSocket client and server functionality into C++ programs
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - /*
